#ifndef _COUNT_CONFIG_H
#define _COUNT_CONFIG_H 1

/*
** This file is automatically generated by the Configure script 
** Count-config written by muquit@semcor.com
** Counter Version: 2.3
** created on: Wed Sep 25 15:30:41 CDT 1996
**
**  If you edit this file, you better make sure you know what are 
**  you doing.
*/
#define ConfigDir "/usr/home/darke/lib/www/wwwcount2.3/conf"
#define ConfigFile "count.cfg"
#define DataDir "/usr/home/darke/lib/www/wwwcount2.3/data"
#define DigitDir "/usr/home/darke/lib/www/wwwcount2.3/digits"
#define LogDir "/usr/home/darke/lib/www/wwwcount2.3/Log"
#define LogFile "Count2.3.log"

/*****************************************************************************
* Defaults parameters not supplied in calling.
* Change 'em here if you insist...
*****************************************************************************/
#define DefaultMaxDigits       6      /* Max digits in output        */
#define DefaultLeftpad         True   /* 0 indicates no padding      */

#define DefaultThickness       6       /* 0 indicates no frame        */
#define Default_FrameRed       100
#define DefaultFrameGreen      139      /* RGB=0;0;0 for black         */
#define DefaultFrameBlue       216
#define FRGB_ImpliedFt         5       /* Use this FT if we get FRGB only */

#define DefaultTransparency       False    /* 0 indicates no transparent  */
#define DefaultTransparentRed     0
#define DefaultTransparentGreen   0 /* RGB=255;255;255 for white   */
#define DefaultTransparentBlue    0
#define TRGBImpliedTr              1   /* Use this TR if we get TRRBG only */

#define DefaultStartCount          1      /* Initial counter value       */
#define DefaultShowCount           1      /* 1 indicates count is shown  */
#define DfForRandom            "RANDOM"    /* This DF name means use rand */
#define DefaultDatafile        "RANDOM"    /* Make rand the default, too  */

#define DefaultDigitsStyle       "A" /* Use GIFs in digits/A/files  */
#define ParamDelimiters           "|&"    /* These separate params       */

/*****************************************************************************
* This specifies a file listing RGB values mapped to names.
* If not defined, no attempt to use RGB names is made.  If you're not sure,   
* just leave this be--it's okay if the file does not exist.
*
* When RGB_MAPPING_ISERROR is set to 1, an error is returned when RGB name
* value is used, but it shows the corresponding RGB triplet.  This is done
* so RGB names can be looked up, but yet not allow users to make constant
* use of this very ineffiecient lookup.
*****************************************************************************/
#define RgbMappingDict        "/usr/home/darke/lib/www/wwwcount2.3/rgb.txt"
/*****************************************************************************
* End of parameter defaults
*****************************************************************************/
#endif /* _COUNT_CONFIG_H*/
