#!/bin/sh
########
# a program to test Count.cgi 1.5
# by muquit@semcor.com
# 09/17/95
##
# if sh=0, then a 1x1 transparent GIF will be written, it will give a
# illusion. so you can count access to a page but will not display any
# counter, otherwise it should always be 1
# parameters can be separated by & or | or both
#
#QUERY_STRING="ft=6&rotate=1&frgb=#fec035&pad=Y&sh=T|incr=1&dd=E&df=counx.dat"
#QUERY_STRING="df=sample.dat|pad=T|comma=T"
#QUERY_STRING="ft=0&display=clock|dd=D"
#QUERY_STRING="display=clock&tformat=12"
#QUERY_STRING="display=clock&tformat=24"
#QUERY_STRING="df=sample.dat|dd=B"
#QUERY_STRING="Ft=0|DF=sample.dat|NEGATE=t|dd=A|srgb=ffffff|prgb=00ff00"
#QUERY_STRING="ft=2|DF=sample.dat|frgb=gold"
#QUERY_STRING="dd=F|lit=014567891|istrip=T|comma=T"
#QUERY_STRING="lit=123456789|dd=A|comma=T"
#QUERY_STRING="display=clock|dd=E"
#QUERY_STRING="lit=14567891"
#QUERY_STRING="df=RanDom|comma=T|chcolor=T|dd=D"
#QUERY_STRING="display=clock|istrip=T|timezone=GMT+0000"
#QUERY_STRING="timezone=GMT+0600|dd=E|comma=T"
#QUERY_STRING="ft=0|display=clock|timezone=GMT+0000"
#QUERY_STRING="display=clock|chcolor=1|timezone=GMT+0500"
#QUERY_STRING="dd=A|display=clock|istrip=T"
#QUERY_STRING="df=c:/file.dat"
#QUERY_STRING="chcolor=T|display=date|dformat=ddmmyy|dd=B"
QUERY_STRING="dd=D|image=lenna.gif|ft=20|frgb=powderblue"
#QUERY_STRING="lit=04-13-95|ft=2|srgb=green|prgb=ff0000|dd=D"
#QUERY_STRING="lit=0123456"
QUERY_STRING="lit=A1,456-:P"

export QUERY_STRING

# play with authentication 
# replace test.counter.com
HTTP_REFERER="http://www.shadowlands.com/cgi-bin/Count.cgi?aaaa"
export HTTP_REFERER

# play with ignore host
#
REMOTE_ADDR='199.1.96.66'
export REMOTE_ADDR

###
# if you have diplay from ImageMagick, try this
# if you have xv, use xv instead of display
###
./Count.cgi -debug | display -
#./Count.cgi -debug | xv -

##
# or you can write the image to file and display with any image viewer
# here digit image will be written to a file count.gif
##
##
#./Count.cgi -debug > litall.gif

