#ifndef __DAEMONS_H
#define __DAEMONS_H

#include <dirs.h>

#define ADVANCE_D            (DIR_SECURE_DAEMONS+"/advance_d")
#define ALCHEMIST_D          (DIR_SECURE_DAEMONS+"/alchemist_d")
#define ARENA_SAVE_D	     (DIR_SECURE_DAEMONS + "/arena_save_d")
#define ASTRONOMY_D          (DIR_SECURE_DAEMONS+"/astronomy_d")
#define BANISH_D             (DIR_SECURE_DAEMONS+"/banish")
#define BANK_D               (DIR_SECURE_DAEMONS+"/bank_d")
#define BBOARD_D             (DIR_SECURE_DAEMONS+"/bboard_d")
#define CASTLE_D             (DIR_DAEMONS+"/castle_d")
#define CHAT_D               (DIR_DAEMONS+"/chat")
#define CLAN_D               (DIR_DAEMONS+"/clan_d")
#define CLOCK_D              (DIR_SECURE_DAEMONS+"/clock_d")
#define CMD_D                (DIR_DAEMONS+"/command")
#define DAMAGE_D	     (DIR_DAEMONS+"/damage_d")
#define ECONOMY_D            (DIR_DAEMONS+"/economy_d")
#define EMAIL_D		     (DIR_DAEMONS+"/email_d")
#define EVENTS_D             (DIR_DAEMONS+"/events_d")
#define FINGER_D             (DIR_SECURE_DAEMONS+"/finger_d")
#define GUILD_D              (DIR_SECURE_DAEMONS+"/guild_d")
#define CRASH_D		    (DIR_DAEMONS+"/crash_items_d")
#define GUILD2_D             (DIR_SECURE_DAEMONS+"/guild2_d")
#define HUNTING_D	     (DIR_SECURE_DAEMONS+"/hunting_d")
#define INACTIVITY_D	     (DIR_SECURE_DAEMONS+"/inactivity_d")
#define INFORM_D	     (DIR_DAEMONS+"/inform_d")
#define LANG_D               (DIR_SECURE_DAEMONS+"/lang_d")
#define LETTER_D             (DIR_DAEMONS+"/letter")
#define LOCALPOST_D          (DIR_DAEMONS+"/localpost")
#define LOCK_D		     (DIR_DAEMONS + "/lock_d")
#define MULTI_D              (DIR_DAEMONS+"/multi_d")
#define NETWORK_D            (DIR_DAEMONS+"/network")
#define NEWS_D               (DIR_SECURE_DAEMONS+"/news_d")
#define PARTY_D              (DIR_SECURE_DAEMONS+"/party_d")
#define PASSWD_D             (DIR_MORTAL_CMDS+"/_passwd")
#define PLAYER_D             (DIR_DAEMONS+"/player_d")
#define RACE_D               (DIR_SECURE_DAEMONS+"/race_d")
#define REINC_D		     (DIR_DAEMONS+"/reinc_d")
#define REFS_D               (DIR_SECURE_DAEMONS+"/refs_d")
#define REMOTEPOST_D         (DIR_DAEMONS+"/remotepost")
#define RITUAL_D             (DIR_SECURE_DAEMONS+"/ritual_d")
#define ROLECALL_D           (DIR_DAEMONS+"/www/rolecall")
#define SAVEALL_D            (DIR_DAEMONS+"/save_all_d")
#define SAVE_ITEMS_D	     (DIR_SECURE_DAEMONS+"/save_items_d")
#define SERVICES_D           (DIR_DAEMONS+"/services")
#define SHELL_D		     (DIR_SECURE_DAEMONS+"/shell_d")
#define SHUT_D               (DIR_SECURE_DAEMONS+"/shutdown_d")
#define SKILLS_D             (DIR_SECURE_DAEMONS+"/skills_d")
#define SOUL_D               (DIR_CMDS+"/soul/atmos")
#define SU_D                 (DIR_SECURE_DAEMONS+"/su_d")
#define TERMINAL_D           (DIR_DAEMONS+"/terminal_d")
#define TIME_D               (DIR_DAEMONS+"/timezones")
#define VIRTUAL_D            (DIR_SECURE_DAEMONS+"/virtual_d")
#define VOTING_D             (DIR_DAEMONS+"/voting")
#define VOTE      (DIR_DAEMONS+"/voter")
#define TELL_CLEAN_D            (DIR_DAEMONS+"/tell_clean_d")

#endif /* __DAEMONS_H */
