{
  "__PACKAGE_UIDS__", "",
  "__LOCALS_IN_TRACEBACK__", "",
  "__SBRK_OK__", "",
  "__CFG_MAX_LOCAL_VARIABLES__", "50",
  "__SUPPRESS_ARGUMENT_WARNINGS__", "",
  "__CALLOUT_HANDLES__", "",
  "__SAVE_EXTENSION__", "\".o\"",
  "__DEFAULT_PRAGMAS__", "PRAGMA_WARNINGS + PRAGMA_STRICT_TYPES + PRAGMA_ERROR_CONTEXT",
  "__GET_CHAR_IS_BUFFERED__", "",
  "__CONFIG_FILE_DIR__", "\"/u/tim/COMP/bin\"",
  "__USE_32BIT_ADDRESSES__", "",
  "__HEARTBEAT_INTERVAL__", "2000000",
  "__SYSMALLOC__", "",
  "__ARRAY_STATS__", "",
  "__OLD_TYPE_BEHAVIOR__", "",
  "__ARGUMENTS_IN_TRACEBACK__", "",
  "__AUTO_TRUST_BACKBONE__", "",
  "__SMALL_STRING_SIZE__", "1000",
  "__HEART_BEAT_CHUNK__", "64",
  "__PACKAGE_CONTRIB__", "",
  "__FLUSH_OUTPUT_IMMEDIATELY__", "",
  "__OLD_ED__", "",
  "__OLD_RANGE_BEHAVIOR__", "",
  "__CACHE_STATS__", "",
  "__LARGE_STRING_SIZE__", "100000",
  "__APPLY_CACHE_BITS__", "14",
  "__BINARIES__", "",
  "__STRING_STATS__", "",
  "__NO_ANSI__", "",
  "__CFG_MAX_CALL_DEPTH__", "100",
  "__LOG_CATCHES__", "",
  "__COMPAT_32__", "",
  "__MAX_SAVE_SVALUE_DEPTH__", "100",
  "__MUDLIB_ERROR_HANDLER__", "",
  "__CFG_EVALUATOR_STACK_SIZE__", "2000",
  "__CALLOUT_CYCLE_SIZE__", "256",
  "__PACKAGE_SOCKETS__", "",
  "__CFG_LIVING_HASH_SIZE__", "4096",
  "__TRACE_CODE__", "",
  "__THIS_PLAYER_IN_CALL_OUT__", "",
  "__NONINTERACTIVE_STDERR_WRITE__", "",
  "__MESSAGE_BUFFER_SIZE__", "16384",
  "__TRACE__", "",
  "__STRIP_BEFORE_PROCESS_INPUT__", "",
  "__HAS_STATUS_TYPE__", "",
  "__NEXT_MALLOC_DEBUG__", "",
  "__AUTO_SETEUID__", "",
  "__PROFILE_FUNCTIONS__", "",
  "__TRAP_CRASHES__", "",
  "__LARGEST_PRINTABLE_STRING__", "16384",
  "__CUSTOM_CRYPT__", "",
  "__PACKAGE_DEVELOP__", "",
  "__PRIVS__", "",
  "__PACKAGE_MATRIX__", "",
  "__PACKAGE_MATH__", "",
  "__PACKAGE_PARSER__", "",
  "__PACKAGE_MUDLIB_STATS__", "",
};

#define NUM_OPTION_DEFS 57

